#!/usr/bin/env bash

# Comment the follow line out if an old docker image is need for running tests
docker pull eventhorizontelescope/eat-notebook

function run-postproc {
	for d in "./postproc-$1"/[1-9].*; do
		echo $(printf "%.0s-" {1..64})
		echo "$d"
		pushd "$d" > /dev/null
		bin/0.launch --docker bash -lic 'for x in bin/[1-8].*; do $x; done'
		# bin/9.next # postproc doesn't need to copy data to the next stage
		popd > /dev/null
	done
}

run-postproc aips-lo
run-postproc casa-lo
run-postproc hops-lo

run-postproc aips-hi
run-postproc casa-hi
run-postproc hops-hi
